### ISSUE TITLE
Configure Github organization

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/infra#2]
## Description

We want our Github settings to be configured via Terraform so it can be versioned et reviewed before we make changes.

## Tasks

- [ ] Set up Terraform
- [ ] Declare repositories
- [ ] Declare organization members
- [ ] Declare branch protection rules
- [ ] Declare shared labels
- [ ] Configure webhooks with Discord integration for code updates and comments
